//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CT239_NienLuan_QLBH
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public string DonViTinh { get; set; }
        public decimal DonGiaBan { get; set; }
        public decimal DonGiaNhap { get; set; }
        public int SoLuongNhap { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public int MaLoaiSP { get; set; }
    }
}
